from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Tuple, Dict
from time import time

from main import (
    Cell,
    CellType,
    get_crystal_cells,
    get_eggs_cells,
    make_chain,
    make_lines,
    number_ants,
    calculate_all_distances,
)

cells = [
    Cell(
        index=0,
        cell_type=CellType.CRYSTAL,
        resources=46,
        initial_resources=46,
        neighbors=[1, 2],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=1,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[3, 5, 0],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=2,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[0, 4, 6],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=3,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[13, 5, 1, 28],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=4,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[2, 27, 14, 6],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=5,
        cell_type=CellType.EGG,
        resources=18,
        initial_resources=18,
        neighbors=[15, 7, 1, 3],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=6,
        cell_type=CellType.EGG,
        resources=18,
        initial_resources=18,
        neighbors=[2, 4, 16, 8],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=7,
        cell_type=CellType.EGG,
        resources=14,
        initial_resources=14,
        neighbors=[15, 17, 19, 9, 5],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=8,
        cell_type=CellType.EGG,
        resources=14,
        initial_resources=14,
        neighbors=[10, 6, 16, 18, 20],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=9,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[7, 19, 21, 11],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=10,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[12, 8, 20, 22],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=11,
        cell_type=CellType.EGG,
        resources=13,
        initial_resources=13,
        neighbors=[9, 21, 23, 25],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=12,
        cell_type=CellType.EGG,
        resources=13,
        initial_resources=13,
        neighbors=[26, 10, 22, 24],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=13,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[29, 3, 28, 38],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=14,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[4, 27, 37, 30],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=15,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[31, 33, 17, 7, 5],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=16,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[8, 6, 32, 34, 18],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=17,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[33, 19, 7, 15],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=18,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[20, 8, 16, 34],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=19,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[17, 21, 9, 7],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=20,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[22, 10, 8, 18],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=21,
        cell_type=CellType.EGG,
        resources=11,
        initial_resources=11,
        neighbors=[19, 23, 11, 9],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=22,
        cell_type=CellType.EGG,
        resources=11,
        initial_resources=11,
        neighbors=[24, 12, 10, 20],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=23,
        cell_type=CellType.CRYSTAL,
        resources=44,
        initial_resources=44,
        neighbors=[21, 35, 25, 11],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=24,
        cell_type=CellType.CRYSTAL,
        resources=44,
        initial_resources=44,
        neighbors=[36, 26, 12, 22],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=25,
        cell_type=CellType.CRYSTAL,
        resources=50,
        initial_resources=50,
        neighbors=[11, 23, 35, 27],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=26,
        cell_type=CellType.CRYSTAL,
        resources=50,
        initial_resources=50,
        neighbors=[28, 12, 24, 36],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=27,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[25, 37, 14, 4],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=28,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[38, 13, 3, 26],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=29,
        cell_type=CellType.CRYSTAL,
        resources=42,
        initial_resources=42,
        neighbors=[41, 31, 13],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=30,
        cell_type=CellType.CRYSTAL,
        resources=42,
        initial_resources=42,
        neighbors=[14, 42, 32],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=31,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[41, 43, 33, 15, 29],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=32,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[16, 30, 42, 44, 34],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=33,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[43, 17, 15, 31],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=34,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[18, 16, 32, 44],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=35,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[23, 25],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=36,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[26, 24],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=37,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[27, 45, 47, 14],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=38,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[48, 13, 28, 46],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=39,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[49, 51, 48, 62],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=40,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[47, 61, 50, 52],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=41,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[53, 55, 43, 31, 29],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=42,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[32, 30, 54, 56, 44],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=43,
        cell_type=CellType.CRYSTAL,
        resources=49,
        initial_resources=49,
        neighbors=[55, 33, 31, 41],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=44,
        cell_type=CellType.CRYSTAL,
        resources=49,
        initial_resources=49,
        neighbors=[34, 32, 42, 56],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=45,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[57, 59, 47, 37],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=46,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[60, 48, 38, 58],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=47,
        cell_type=CellType.EGG,
        resources=11,
        initial_resources=11,
        neighbors=[37, 45, 59, 61, 40],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=48,
        cell_type=CellType.EGG,
        resources=11,
        initial_resources=11,
        neighbors=[62, 39, 38, 46, 60],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=49,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[51, 39, 62],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=50,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[40, 61, 52],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=51,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[53, 39, 49],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=52,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[40, 50, 54],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=53,
        cell_type=CellType.CRYSTAL,
        resources=52,
        initial_resources=52,
        neighbors=[55, 41, 51],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=54,
        cell_type=CellType.CRYSTAL,
        resources=52,
        initial_resources=52,
        neighbors=[42, 52, 56],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=55,
        cell_type=CellType.EGG,
        resources=19,
        initial_resources=19,
        neighbors=[43, 41, 53],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=56,
        cell_type=CellType.EGG,
        resources=19,
        initial_resources=19,
        neighbors=[44, 42, 54],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=57,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[59, 45],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=58,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[60, 46],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=59,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[45, 57, 61, 47],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=60,
        cell_type=CellType.EMPTY,
        resources=0,
        initial_resources=0,
        neighbors=[62, 48, 46, 58],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=61,
        cell_type=CellType.CRYSTAL,
        resources=41,
        initial_resources=41,
        neighbors=[47, 59, 50, 40],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
    Cell(
        index=62,
        cell_type=CellType.CRYSTAL,
        resources=41,
        initial_resources=41,
        neighbors=[49, 39, 48, 60],
        my_ants=0,
        opp_ants=0,
        routes={},
    ),
]

start_t = time()
crystal_cells = get_crystal_cells(cells)
eggs_cells = get_eggs_cells(cells)
base = cells[41]
target_cells = [*crystal_cells, *eggs_cells]
# t = initilize_distances(target_cells, cells)
# print(t[0])

# print(
#     make_chain(
#         base,
#         target_cells.copy(),
#         cells,
#         2,
#     )
# )
# print([cell for cell in cells if cell.routes.get(26) is None])
# print(make_lines(cells[41], cells[44]))
# print(t)
# print(cells[41].routes[cells[44].index][0])
cells = calculate_all_distances(cells)
print(cells[0].routes[1][0])
end_t = time()
print("Duration: ", end_t - start_t)
